apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
    name: amsdemo
spec:
    broker: default
    filter: {}
    subscriber:
        ref:
            apiVersion: serving.knative.dev/v1alpha1
            kind: Service
            name: call-lambda
